go: '1.21'

#run:

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

skip-dirs:
  - src/http_server

linters:
  disable:
    - ineffassign
    - staticcheck
  enable:
     - goimports
     - exportloopref
     - gosec
     - nilerr
     - predeclared
     - durationcheck


output:
  print-linter-name: true
  sort-results: true

linters-settings:
  gosimple:
    checks: [ "all", "-S1034", "-SA4006", "-S1017" ]

  nolintlint:
    allow-unused: true




revive:
  rules:
    - name: unused-parameter
      disabled: true