go: '1.21'

run:
  tests: false

issues:
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013

  max-issues-per-linter: 0
  max-same-issues: 0

skip-dirs:
  - src/http_server

linters:
  enable:
     - goimports
     - exportloopref
     - gosec
     - nilerr
     - predeclared
#    - bodyclose
#    - revive
#    - rowserrcheck
#    - tparallel
#    - unconvert
#    - unparam


output:
  print-linter-name: true
  sort-results: true


gofmt:
  simplify: true
  # Apply the rewrite rules to the source before reformatting.
  # https://pkg.go.dev/cmd/gofmt
  # Default: []
  rewrite-rules:
    - pattern: 'interface{}'
      replacement: 'any'
    - pattern: 'a[b:len(a)]'
      replacement: 'a[b:]'
